version: "3.8"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    # environment:
    #   - ACME_DNS_API_BASE=https://auth.acme-dns.io
    #   - ACME_DNS_STORAGE_PATH=/acme-dns
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/traefik/traefik.yml:/traefik.yml:ro
      - /opt/docker/traefik/acme.json:/acme.json
      # - /var/www/traefik/acme-dns:/acme-dns
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.mynetdisk.top`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  mysql:
    # build:
    #   context: ./blog-database
    #   dockerfile: ./Dockerfile
    # image: mysql:latest
    image: mynetdisk/react-blog-database:latest
    container_name: mysql
    restart: always
    volumes:
      - /opt/docker/mysql/data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "ADMIN_USER_NAME=admin"
      - "ADMIN_USER_PASSWORD=123456"
    ports:
      - "3306:3306"
    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8888:80"
    environment:
      - "PMA_HOST=mysql"
    networks:
      - proxy
    labels:
      # 设置Host进行域名访问
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=https"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.mynetdisk.top`)"

  eggjs:
    # build:
    #   context: ./blog-server
    #   dockerfile: ./Dockerfile
    # image: eggjs:latest
    image: mynetdisk/react-blog-server:latest
    container_name: eggjs
    restart: always
    environment:
      - "MYSQL_ROOT_HOST=mysql"
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "7001:7001"
    labels:
      # 设置Host进行域名访问
      - "traefik.enable=true"
      - "traefik.http.routers.eggjs.entrypoints=https"
      - "traefik.http.routers.eggjs.rule=Host(`api.mynetdisk.top`)"
      - "traefik.http.services.eggjs.loadbalancer.server.port=7001"
    depends_on:
      - mysql
    networks:
      - proxy

  admin:
    # build:
    #   context: ./blog-admin
    #   dockerfile: ./Dockerfile
    # image: admin:latest
    image: mynetdisk/react-blog-admin:latest
    container_name: admin
    restart: always
    ports:
      - "3000:3000"
    labels:
      # 设置Host进行域名访问
      - "traefik.enable=true"
      - "traefik.http.routers.admin.entrypoints=https"
      - "traefik.http.routers.admin.rule=Host(`admin.mynetdisk.top`)"
      - "traefik.http.services.admin.loadbalancer.server.port=3000"
    depends_on:
      - eggjs
    networks:
      - proxy

  blog:
    # build:
    #   context: ./blog
    #   dockerfile: ./Dockerfile
    # image: admin:latest
    image: mynetdisk/react-blog-web:latest
    container_name: blog
    restart: always
    ports:
      - "3001:3001"
    labels:
      # 设置Host进行域名访问
      - "traefik.enable=true"
      - "traefik.http.routers.blog.entrypoints=https"
      - "traefik.http.routers.blog.rule=Host(`blog.mynetdisk.top`)"
      - "traefik.http.services.blog.loadbalancer.server.port=3001"
    depends_on:
      - eggjs
    networks:
      - proxy

networks:
  proxy:
    external: true
